# Change these first
owner: rbarbazz # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: raphaelbarbazza.com
    url: https://www.raphaelbarbazza.com
  - name: mysustainablesanctuary.com
    url: https://mysustainablesanctuary.com
